### ISSUE TITLE
Webpage Crash Because my Sqllite file is 900MB

### ISSUE THREAD

**Issue by watchesbrands** [lbalogh/WhatsAppDBReader#1]
Facing Browser Crash because of big file size (900MB)
Is There is an alternative free software to export data from it

I have to copy all the contacts number which people message me on Whatsapp

**Comment by lbalogh** [comment]
Well.. it's JavaScript based so not surprising it crashes with such a big db file. Depending of what data you need to extract, you can use DB Browser for SQLite, it can export query results in CSV

**Comment by watchesbrands** [comment]
DB Browser for SQLite show its not a database file ..
then i try too many sqllite software

(Sqllite Studio works for me https://www.filehorse.com/download-sqlitestudio/)

My problem is solved 

Thank you for your reply.
